### ISSUE TITLE
split pipelines on %>%

### ISSUE THREAD

**Issue by jzelner** [yihui/formatR#62] opened 2017-02-21 14:06 UTC
Love the package, but would it be possible to allow pipelines to have each operator on a separate line, so:

d2 <- d %>% 
          group_by(age) %>%
          summarize(height = mean(height))

I think this would make for much cleaner pipelines, as in long ones, operators are currently split over multiple lines. 

Thanks!

-Jon Zelner

**Comment by yihui** [comment] 2017-02-21 19:49
Duplicate of #54...

**Comment by calenwalshe** [comment] 2017-05-27 16:12
I followed the thread links to the earliest reference to this question. It appears that the answer is that you won't be implementing it because deparse() doesn't handle '%>%' in the way this request is asking for?

Are there any plans to have formatR handle dplyr pipes in this way? I love formatR but I use dplyr chains so extensively that formatR makes my dplyr code unreadable.

Can you suggest any workarounds to make this work?

thanks.

**Comment by yihui** [comment] 2017-05-27 23:11
#68 might solve the problem, but I'm not completely sure.

**Closed** 2021-03-15 21:58 UTC

**Comment by yihui** [comment] 2021-03-15 22:04
This has been implemented. You can install the development version via

```r
remotes::install_github('yihui/formatR')
```

Thanks!
